spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/spring
    password: test1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
springboot:
  jwt:
    secret: flature!@#flature!@#flature!@#flature!@#flature!@#flature!@#
